  
  const rows = [
      { id: 1, lastName: "Snow", firstName: "Jon", age: 35 },
      { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
      { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
      { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
      { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
      { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
      { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
      { id: 8, lastName: "Frances", firstName: "Rossini", age: 36 },
      { id: 9, lastName: "Roxie", firstName: "Harvey", age: 65 },
      { id: 10, lastName: "Snow", firstName: "Jon", age: 35 },
      { id: 11, lastName: "Ramir", firstName: "Suhri", age: 31 },
      { id: 12, lastName: "Lannister", firstName: "Cersei", age: 22 },
      { id: 13, lastName: "Lannister", firstName: "Jaime", age: 25 },
      { id: 14, lastName: "Stark", firstName: "Arya", age: 26 },
      { id: 15, lastName: "Targaryen", firstName: "Daenerys", age: null },
      { id: 16, lastName: "Melisandre", firstName: null, age: 57 },
      { id: 17, lastName: "Clifford", firstName: "Ferrara", age: 54 },
      { id: 18, lastName: "Frances", firstName: "Rossini", age: 56 },
      { id: 19, lastName: "Roxie", firstName: "Harvey", age: 45 },
      { id: 20, lastName: "Marek", firstName: "Marek", age: 39 },
    ];